version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - formats: [ 'tar.gz' ]
    files:
      - LICENSE
signs:
  - id: archive-keyless
    cmd: cosign
    artifacts: archive
    signature: ${artifact}.sigstore
    output: false
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "-y"
